- hosts: all
  sudo: true
  tasks:
  
     - name: Download Java JDK
       get_url:
         url: http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.rpm
         dest: /opt/jdk-8u191-linux-x64.rpm
         headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
     - name: Install Java JDK rpm from a local file
       yum:
         name: /opt/jdk-8u191-linux-x64.rpm
         state: present

     - blockinfile:
         path: /etc/profile
         block: |
           export JAVA_HOME=/usr/java/jdk1.8.0_191-amd64
           export PATH=$PATH:$JAVA_HOME/bin
     - name: Download ant
       unarchive:
         src: http://mirrors.estointernet.in/apache//ant/binaries/apache-ant-1.10.5-bin.zip
         dest: /opt
         remote_src: yes
     - name: set ant path
       blockinfile:
         path: /etc/profile
         block: |
           export ANT_HOME=/opt/apache-ant-1.10.5
           export PATH=$PATH:$ANT_HOME/bin
     - name: Download Maven
       unarchive:
         src: http://mirrors.estointernet.in/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
         dest: /opt
         remote_src: yes
     - name: set Maven path
       blockinfile:
         path: /etc/profile
         block: |
           export M2_HOME=/opt/apache-maven-3.6.0
           export PATH=$PATH:$M2_HOME/bin
     - name: Download Gradle
       unarchive:
         src: https://services.gradle.org/distributions/gradle-4.10.2-all.zip
         dest: /opt
         remote_src: yes
     - name: set gradle path
       blockinfile:
         path: /etc/profile
         block: |
           export GRADLE_HOME=/opt/gradle-4.10.2
           export PATH=$PATH:$GRADLE_HOME/bin
     - name: Download Scanner
       unarchive:
         src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
         dest: /opt
         remote_src: yes
     - name: set Sonar Scanner path
       blockinfile:
         path: /etc/profile
         block: |
           export SONAR_SCANNER=/opt/sonar-scanner-3.2.0.1227-linux
           export PATH=$PATH:$SONAR_SCANNER/bin
     - name: Download apache-tomcat
       unarchive:
         src: http://mirrors.wuchna.com/apachemirror/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.zip
         dest: /opt
         remote_src: yes
     - name: Download wildfly
       unarchive:
         src: http://download.jboss.org/wildfly/14.0.1.Final/wildfly-14.0.1.Final.zip
         dest: /opt
         remote_src: yes
     - name: Download Nexus
       unarchive:
         src: https://github.com/Yphanikumar5/nexus/archive/nexus.zip
         dest: /opt
         remote_src: yes
     - name: Download Jfrog
       unarchive:
         src: https://github.com/Yphanikumar5/jfrog/archive/jfrog.zip
         dest: /opt
         remote_src: yes
     - name: Download SonarQube
       unarchive:
         src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.4.zip
         dest: /opt
         remote_src: yes
     - name: download jenkins.repo
       get_url:
          url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo

     - name: import jenkins key
       rpm_key:
         state: present
         key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

     - name: install jenkins
       yum:
         name: jenkins
         state: present
     - name: Install the docker
       yum: name={{item}} state=installed
       with_items:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
       - ftp://bo.mirror.garr.it/1/slc/centos/7.1.1503/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
     - name: Add Docker repo
       get_url:
         url: https://download.docker.com/linux/centos/docker-ce.repo
         dest: /etc/yum.repos.d/docer-ce.repo
       become: yes

     - name: Enable Docker Edge repo
       ini_file:
         dest: /etc/yum.repos.d/docer-ce.repo
         section: 'docker-ce-edge'
         option: enabled
         value: 0
       become: yes

     - name: Enable Docker Test repo
       ini_file:
         dest: /etc/yum.repos.d/docer-ce.repo
         section: 'docker-ce-test'
         option: enabled
         value: 0
       become: yes

     - name: Install Docker
       yum:
         name: docker-ce
         state: latest
       become: yes
