---
- name: Download and install jenkins
  hosts: all
  sudo: true
  tasks:


     - name: Install the docker
       yum: name={{item}} state=installed
       with_items:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
       - ftp://bo.mirror.garr.it/1/slc/centos/7.1.1503/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
     - name: Add Docker repo
       get_url:
         url: https://download.docker.com/linux/centos/docker-ce.repo
         dest: /etc/yum.repos.d/docer-ce.repo
       become: yes

     - name: Enable Docker Edge repo
       ini_file:
         dest: /etc/yum.repos.d/docer-ce.repo
         section: 'docker-ce-edge'
         option: enabled
         value: 0
       become: yes

     - name: Enable Docker Test repo
       ini_file:
         dest: /etc/yum.repos.d/docer-ce.repo
         section: 'docker-ce-test'
         option: enabled
         value: 0
       become: yes

     - name: Install Docker
       yum:
         name: docker-ce
         state: latest
       become: yes
