- hosts: all
  sudo: true
  tasks:

  - name: Download Java JDK
    get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.rpm
      dest: /opt/jdk-8u191-linux-x64.rpm
      headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
  - name: Install Java JDK rpm from a local file
    yum:
      name: /opt/jdk-8u191-linux-x64.rpm
      state: present

  - blockinfile:
      path: /etc/profile
      block: |
        export JAVA_HOME=/usr/java/jdk1.8.0_191-amd64
        export PATH=$PATH:$JAVA_HOME/bin
